[package]
name = "client"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
log = "0.4"
env_logger = "0.9"
common = { path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }
rand = "0.9.0"
byteorder = "1.5.0"