[workspace]
members = [
    "client",
    "server",
    "common",
]

resolver = "2"
log = "0.4"
env_logger = "0.9"
[workspace.dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1"

